/**
 * Les 99 langues reconnues par Whisper, tirées de son tokenizer officiel.
 * Le code ISO sert à la transcription, le nom au prompt de traduction.
 *
 * Doit rester aligné avec mobile/src/constants/languages.ts.
 */
export const LANGUAGES: Record<string, string> = {
  fr: 'français',
  en: 'anglais',
  es: 'espagnol',
  de: 'allemand',
  it: 'italien',
  pt: 'portugais',
  ar: 'arabe',
  zh: 'chinois mandarin',
  ja: 'japonais',
  ru: 'russe',
  af: 'afrikaans',
  sq: 'albanais',
  am: 'amharique',
  hy: 'arménien',
  as: 'assamais',
  az: 'azéri',
  ba: 'bachkir',
  eu: 'basque',
  bn: 'bengali',
  my: 'birman',
  be: 'biélorusse',
  bs: 'bosniaque',
  br: 'breton',
  bg: 'bulgare',
  yue: 'cantonais',
  ca: 'catalan',
  ko: 'coréen',
  hr: 'croate',
  ht: 'créole haïtien',
  da: 'danois',
  et: 'estonien',
  fi: 'finnois',
  fo: 'féroïen',
  gl: 'galicien',
  cy: 'gallois',
  el: 'grec',
  gu: 'gujarati',
  ka: 'géorgien',
  ha: 'haoussa',
  haw: 'hawaïen',
  hi: 'hindi',
  hu: 'hongrois',
  he: 'hébreu',
  id: 'indonésien',
  is: 'islandais',
  jw: 'javanais',
  kn: 'kannada',
  kk: 'kazakh',
  km: 'khmer',
  lo: 'lao',
  la: 'latin',
  lv: 'letton',
  ln: 'lingala',
  lt: 'lituanien',
  lb: 'luxembourgeois',
  mk: 'macédonien',
  ms: 'malais',
  ml: 'malayalam',
  mg: 'malgache',
  mt: 'maltais',
  mi: 'maori',
  mr: 'marathi',
  mn: 'mongol',
  no: 'norvégien',
  nn: 'norvégien nynorsk',
  nl: 'néerlandais',
  ne: 'népalais',
  oc: 'occitan',
  ur: 'ourdou',
  uz: 'ouzbek',
  ps: 'pachto',
  pa: 'pendjabi',
  fa: 'persan',
  pl: 'polonais',
  ro: 'roumain',
  sa: 'sanskrit',
  sr: 'serbe',
  sn: 'shona',
  sd: 'sindhi',
  si: 'singhalais',
  sk: 'slovaque',
  sl: 'slovène',
  so: 'somali',
  su: 'soundanais',
  sv: 'suédois',
  sw: 'swahili',
  tg: 'tadjik',
  tl: 'tagalog',
  ta: 'tamoul',
  tt: 'tatar',
  cs: 'tchèque',
  th: 'thaï',
  bo: 'tibétain',
  tr: 'turc',
  tk: 'turkmène',
  te: 'télougou',
  uk: 'ukrainien',
  vi: 'vietnamien',
  yi: 'yiddish',
  yo: 'yoruba',
};

export function languageName(code: string): string {
  return LANGUAGES[code] || code;
}

export function isSupported(code: string): boolean {
  // 'auto' n'est pas une langue mais une consigne : laisser Whisper
  // détecter. Valide en source uniquement, jamais en cible.
  if (code === 'auto') return true;
  return code in LANGUAGES;
}
